name: 'windows-release'
on:
  push:
    branches:
      - release

concurrency:
  group: 'windows-release-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  windows-release-release-d3d:
    runs-on: windows-2022
    env: 
      SKIA_DEBUG: 0

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1.4.0
      with:
        rust-version: stable

    - name: Install Clippy
      run: rustup component add clippy
      shell: bash

    - name: Python Version
      run: python --version

    - name: Upgrade LLVM
      run: choco upgrade llvm
    - name: 'Install Rust target x86_64-pc-windows-msvc'
      shell: bash
      run: |
        rustup target add x86_64-pc-windows-msvc

    - name: 'Build skia-safe for x86_64-pc-windows-msvc with features d3d,freetype-woff2,embed-freetype'
      shell: bash
      run: |
        if [ "false" == "true" ]; then
          TARGET=x86_64-pc-windows-msvc
          TARGET=${TARGET//-/_}
          export CC_${TARGET}=x86_64-pc-windows-msvc26-clang.exe
          export CXX_${TARGET}=x86_64-pc-windows-msvc26-clang++.exe
          export AR_${TARGET}=llvm-ar
          TARGET_UPPERCASE=`echo "${TARGET}" | tr [a-z] [A-Z]`
          export CARGO_TARGET_${TARGET_UPPERCASE}_LINKER=x86_64-pc-windows-msvc26-clang.exe
          echo "Set CC, CXX, and CARGO_LINKER target specific environment variables for Android"
        fi
        if [ "false" == "true" ]; then
          source /emsdk/emsdk_env.sh
        fi
        cargo clean
        cargo build -p skia-safe --release --features "d3d,freetype-woff2,embed-freetype" --target x86_64-pc-windows-msvc
        echo "SKIA_BINARIES_TAG=$(cat "${BUILD_ARTIFACTSTAGINGDIRECTORY}/skia-binaries/tag.txt")" >> ${GITHUB_ENV}
        echo "SKIA_BINARIES_KEY=$(cat "${BUILD_ARTIFACTSTAGINGDIRECTORY}/skia-binaries/key.txt")" >> ${GITHUB_ENV}
        echo "SKIA_STAGING_PATH=${BUILD_ARTIFACTSTAGINGDIRECTORY}" >> ${GITHUB_ENV}
      env:
        BUILD_ARTIFACTSTAGINGDIRECTORY: ${{ runner.temp }}

    - name: 'Compress binaries'
      if: true
      uses: a7ul/tar-action@v1.1.2
      with:
        command: c
        cwd: '${{ env.SKIA_STAGING_PATH }}'
        files: 'skia-binaries'
        outPath: '${{ runner.temp }}/skia-binaries-${{ env.SKIA_BINARIES_KEY }}.tar.gz'

    - name: 'Release binaries'
      if: true
      uses: pragmatrix/release-action@v1.11.1-rs
      with:
        owner: namseent
        repo: skia-binaries
        allowUpdates: true
        replacesArtifacts: true
        tag: '${{ env.SKIA_BINARIES_TAG }}'
        artifacts: '${{ runner.temp }}/skia-binaries-${{ env.SKIA_BINARIES_KEY }}.tar.gz'
        artifactErrorsFailBuild: true
        token: ${{ secrets.RUST_SKIA_RELEASE_TOKEN }}
        prerelease: true
